project:
  type: book

book:
  title: "Collection of Links"
  author: "Hamid Bulut"
  date: "1.1.2025"
  chapters:
    - index.qmd
    - intro.qmd
    - c1.qmd
    - c2.qmd
    - c3.qmd
    - c4.qmd
    - c5.qmd
    - c6.qmd
    - c7.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
