# Chapter 6: Psychology, Society, and Human Behavior

- **Psychology experiment detects correlation between thinking of others… (CTV News)**
  <https://www.ctvnews.ca/mobile/climate-and-environment/psychology-experiment-detects-correlation-between-thinking-of-others-countries-environmental-protections-1.5582354>

- **Information Can Reduce Selfish Behavior – Neuroscience News**
  <https://neurosciencenews.com/selfish-behavior-information-19377/amp/>

- **Justice Evaluation of the Income Distribution (JEID): Development and validation…**
  <https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0281021>

- **Human social preferences cluster and spread in the field | PNAS**
  <https://www.pnas.org/doi/10.1073/pnas.2000824117>  [Add to Citavi project by DOI]

- **How extreme heat from climate change distorts human behavior – Science News**
  <https://www.sciencenews.org/article/extreme-heat-climate-change-human-behavior-aggression-equity>

- **Lack of Trust Exacerbates Loneliness Spiral – Neuroscience News**
  <https://neurosciencenews.com/loneliness-trust-19357/amp/>

- **‘Overwhelming and terrifying’: the rise of climate anxiety – The Guardian**
  <https://amp.theguardian.com/environment/2020/feb/10/overwhelming-and-terrifying-impact-of-climate-crisis-on-mental-health>

- **How to discuss climate change productively – CNBC**
  <https://www-cnbc-com.cdn.ampproject.org/v/s/www.cnbc.com/amp/2021/09/26/how-to-discuss-climate-change-productively.html>

- **“Eco-anxiety”: fear of environmental doom weighs on young people – The Guardian**
  <https://www.theguardian.com/society/2021/oct/06/eco-anxiety-fear-of-environmental-doom-weighs-on-young-people>

- **Mit Vertrauen gegen die Unsicherheit – Aktuell Uni Bielefeld**
  <https://aktuell.uni-bielefeld.de/2023/09/19/mit-vertrauen-gegen-die-unsicherheit/?s=09>

- **Die Habermas–Luhmann–Kontroverse: Theorie der Gesellschaft oder Sozialtechnologie?**
  <https://www.lernhelfer.de/schuelerlexikon/politikwirtschaft/artikel/die-habermas-luhmann-kontroverse-theorie-der-gesellschaft#>

- **Some thoughts about the use of cloud services and web APIs in social science research**
  <https://datascience.blog.wzb.eu/2022/03/07/some-thoughts-about-the-use-of-cloud-services-and-web-apis-in-social-science-research/>

- **Sozialtheoristen – Wissenschaft**
  <https://sozialtheoristen.de/category/horizontal/wissenschaft/>

- **The Social Construction of Age: Concepts and Measurement | Annual Reviews**
  <https://www.annualreviews.org/content/journals/10.1146/annurev-soc-031021-121020>
